export const states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'];
export const industries = ["Auto (Car, Motorcycle, Marine..)",
"Marketing and Advertising",
"Construction and Contractors ",
"Distribution and Wholesale",
"Dry Cleaning and Laundry",
"Fast Food and Quick-Service Restaurants",
"Franchise Businesses, Resale, Existing and New Franchise Offers",
"Gas Stations and Car Washes",
"Health Fitness Clubs, Gyms, Nutrition Food Stores",
"Manufacturing, Assembly, and",
"Marine, Boat, Yacht, PWC, Watercraft",
"Media, Publishing, Newspaper, and Magazine",
"Professional Services, Consulting, CPA, Legal, and Financial Practices",
"Financial Investment, Credit, Insurance Services",
"Real Estate, Commercial, and Land",
"Retail Store",
"B2B Services",
"B2C Services",
"Technology, Computing, ISP, and Networking services"];